name: Rust Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y libsqlite3-dev
      
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install sqlite3
      
      - name: Build
        run: cargo build --release
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/libsqlite3_chromaprint.so
            target/release/libsqlite3_chromaprint.dylib
            target/release/sqlite3_chromaprint.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
